### ISSUE TITLE
lact-gui crashes on startup if no GPUs

### ISSUE THREAD

**Issue by Susurrus** [ilyazzz/LACT#14]
Was working and displaying my Vega56 properly the other day, but didn't today:
```
❯ RUST_BACKTRACE=1 lact-gui
Connection to daemon established
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', gui/src/app/header.rs:58:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: <O as gtk::auto::combo_box::ComboBoxExt>::connect_changed::changed_trampoline
   4: g_signal_emit_valist
   5: g_signal_emit
   6: <unknown>
   7: gtk_combo_box_set_active
   8: gui::app::header::Header::set_gpus
   9: gui::app::App::run
  10: gui::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I guessed it was because it didn't detect a GPU, so tried `lact-cli`. Running that I see no GPUs:
```
❯ lact-cli gpus
Ok({})
```

I'm surprised there's no GPU shown, as I'm definitely running a Vega that I'm using to type this, but not certain what's going wrong. Daemon is running fine: `  lactd.service                                                                                           loaded active running   AMDGPU Control Daemon                                    `

**Comment by ilyazzz** [comment]
Can you run this
`sudo systemctl stop lactd`
`sudo RUST_LOG=trace lact-daemon`

This will give verbose output of the daemon's initialization, which should show if there are any errors when initializing the GPU.

**Comment by Susurrus** [comment]
I just stopped and restarted it and now it's working fine:
```
❯ sudo RUST_LOG=trace lact-daemon
[2021-03-04T07:15:57Z TRACE daemon] Using config Config { gpu_configs: {3469417629: (GpuIdentifier { pci_id: "0000:09:00.0", card_model: Some("RX Vega64"), gpu_model: Some("Vega 10 XL/XT [Radeon RX Vega 56/64]"), path: "/sys/class/drm/card0/device" }, GpuConfig { fan_control_enabled: false, fan_curve: {20: 0.0, 40: 0.0, 60: 50.0, 80: 80.0, 100: 100.0}, power_cap: -1, power_profile: Auto, gpu_max_clock: 0, gpu_max_voltage: None, vram_max_clock: 0 })}, config_path: "/etc/lact.json" }
[2021-03-04T07:15:57Z INFO  daemon] Initializing "/sys/class/drm/card0"
[2021-03-04T07:15:57Z INFO  daemon::gpu_controller::vendor_data] Parsing pci.ids
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Seacrhing vendor 1002
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Found vendor Advanced Micro Devices, Inc. [AMD/ATI]
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Searching device 687f
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Found device Vega 10 XL/XT [Radeon RX Vega 56/64]
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Searching subdevice 1002 6b76
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Found subvendor Advanced Micro Devices, Inc. [AMD/ATI]
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller::vendor_data] Found subdevice RX Vega64
[2021-03-04T07:15:57Z INFO  daemon::gpu_controller] Vendor data: VendorData { gpu_vendor: Some("Advanced Micro Devices, Inc. [AMD/ATI]"), gpu_model: Some("Vega 10 XL/XT [Radeon RX Vega 56/64]"), card_vendor: Some("Advanced Micro Devices, Inc. [AMD/ATI]"), card_model: Some("RX Vega64") }
[2021-03-04T07:15:57Z TRACE daemon::hw_mon] setting power cap to -1000000
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Reading clocks table
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_SCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 852MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 991MHz 900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 1084MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 1138MHz 1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 4: 1200MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 5: 1401MHz 1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 6: 1536MHz 1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 7: 1630MHz 1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 167MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 500MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 800MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 945MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock and voltage ranges
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Successfully parsed the clocks table
[2021-03-04T07:15:57Z INFO  daemon::gpu_controller] Writing s 7 0
     to pp_od_clk_voltage
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Reading clocks table
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_SCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 852MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 991MHz 900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 1084MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 1138MHz 1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 4: 1200MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 5: 1401MHz 1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 6: 1536MHz 1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 7: 1630MHz 1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 167MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 500MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 800MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 945MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock and voltage ranges
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Successfully parsed the clocks table
[2021-03-04T07:15:57Z INFO  daemon::gpu_controller] Writing m 3 0 1050
     to pp_od_clk_voltage
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Reading clocks table
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_SCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 852MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 991MHz 900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 1084MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 1138MHz 1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 4: 1200MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 5: 1401MHz 1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 6: 1536MHz 1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 7: 1630MHz 1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 167MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 500MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 800MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 945MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock and voltage ranges
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Successfully parsed the clocks table
[2021-03-04T07:15:57Z TRACE daemon::hw_mon] setting power cap to -1000000
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Reading clocks table
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_SCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 852MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 991MHz 900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 1084MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 1138MHz 1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 4: 1200MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 5: 1401MHz 1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 6: 1536MHz 1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 7: 1630MHz 1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 167MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 500MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 800MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 945MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock and voltage ranges
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Successfully parsed the clocks table
[2021-03-04T07:15:57Z INFO  daemon::gpu_controller] Writing s 7 0
     to pp_od_clk_voltage
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Reading clocks table
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_SCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        852Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 852MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        991Mhz        900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 991MHz 900mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:       1084Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 1084MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:       1138Mhz       1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 1138MHz 1000mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 4:       1200Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 4: 1200MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 5:       1401Mhz       1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 5: 1401MHz 1100mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 6:       1536Mhz       1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 6: 1536MHz 1150mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 7:       1630Mhz       1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 7: 1630MHz 1200mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_MCLK:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 0:        167Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 0: 167MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 1:        500Mhz        800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 1: 500MHz 800mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 2:        800Mhz        950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 2: 800MHz 950mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line 3:        945Mhz       1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Power level 3: 945MHz 1050mV
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing power level line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Finished reading clock levels
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing line OD_RANGE:
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Parsing clock and voltage ranges
[2021-03-04T07:15:57Z TRACE daemon::gpu_controller] Successfully parsed the clocks table
[2021-03-04T07:15:57Z INFO  daemon::gpu_controller] Writing m 3 0 1050
     to pp_od_clk_voltage
[2021-03-04T07:15:57Z INFO  daemon] already known
[2021-03-04T07:15:57Z INFO  daemon::config] saving {"config_path":"/etc/lact.json","gpu_configs":{"3469417629":[{"card_model":"RX Vega64","gpu_model":"Vega 10 XL/XT [Radeon RX Vega 56/64]","path":"/sys/class/drm/card0/device","pci_id":"0000:09:00.0"},{"fan_control_enabled":false,"fan_curve":{"100":100.0,"20":0.0,"40":0.0,"60":50.0,"80":80.0},"gpu_max_clock":0,"gpu_max_voltage":null,"power_cap":-1,"power_profile":"Auto","vram_max_clock":0}]}}
```

Then running `lact-gui`, it showed my GPU no problem. So looks like there might be an init problem somewhere, but I could reproduce it right now.

**Comment by ilyazzz** [comment]
My guess is that the daemon starts too early in the boot process, before the kernel mounts the necessary sysfs interfaces. The service file probably should include something like `After=graphical.target`. I'll look into it.

**Comment by ilyazzz** [comment]
There was a conflict in the service file regarding which systemd target the daemon initializes on. You should update and run `sudo systemctl disable lactd && sudo systemctl enable lactd`, so that it gets installed in the proper runlevel.
