### ISSUE TITLE
thread 'main' panicked at 'No power state'

### ISSUE THREAD

**Issue by iRhonin** [ilyazzz/LACT#2]
Hi, thank you for your awesome tool.
Actually when I run the `lact-gui` i get this error, can you help me to fix this?

Env: `ubuntu 20.04 - 5.4.0-53-generic`

```
Initializing gtk
Activating
Getting elements
Connected
Set current gpu id to 4228809584
changed adjustment value to 130/130
power profile selection changed
Automatic fan control enabled
Setting value 0 on adjustment 1
Setting value 0 on adjustment 2
Setting value 50 on adjustment 3
Setting value 80 on adjustment 4
Setting value 100 on adjustment 5
thread 'main' panicked at 'No power state', gui/src/main.rs:176:60
stack backtrace:
   0:     0x5650da6c88c0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x5650da6c88c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x5650da6c88c0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x5650da6c88c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x5650da6ecfbc - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x5650da6c5e57 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x5650da6cac10 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x5650da6cac10 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x5650da6cac10 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x5650da6ca95c - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x5650da6cb273 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x5650da6cae49 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x5650da6c8d4c - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x5650da6cae09 - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x5650da6eb5c1 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x5650da6eb353 - core::option::expect_failed::hd5a1da3a6b6bbb34
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
  16:     0x5650da6661fe - <O as gtk::auto::combo_box::ComboBoxExt>::connect_changed::changed_trampoline::h8f5d392867f201aa
  17:     0x7f35fe583a56 - <unknown>
  18:     0x7f35fe5a2b28 - g_signal_emit_valist
  19:     0x7f35fe5a30d3 - g_signal_emit
  20:     0x7f35febcca61 - <unknown>
  21:     0x7f35febcf15f - gtk_combo_box_set_active
  22:     0x5650da6598c6 - gui::build_ui::ha54b75bac08fa0ce
  23:     0x5650da666513 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::ha266372dcc215511
  24:     0x7f35fe583802 - g_closure_invoke
  25:     0x7f35fe597814 - <unknown>
  26:     0x7f35fe5a2b9e - g_signal_emit_valist
  27:     0x7f35fe5a30d3 - g_signal_emit
  28:     0x7f35fe6b1d88 - <unknown>
  29:     0x7f35fe6b1f42 - g_application_run
  30:     0x5650da6663fe - <O as gio::application::ApplicationExtManual>::run::h505899b42c7b59c3
  31:     0x5650da65c77b - gui::main::h95de34149aa7743a
  32:     0x5650da65ed73 - std::sys_common::backtrace::__rust_begin_short_backtrace::h631d3f9c2852ed08
  33:     0x5650da65ee09 - std::rt::lang_start::{{closure}}::h462706e82fa81411
  34:     0x5650da6cb671 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  35:     0x5650da6cb671 - std::panicking::try::do_call::h88ce358792b64df0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  36:     0x5650da6cb671 - std::panicking::try::h6311c259678e50fc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  37:     0x5650da6cb671 - std::panic::catch_unwind::h56c5716807d659a1
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  38:     0x5650da6cb671 - std::rt::lang_start_internal::h73711f37ecfcb277
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  39:     0x5650da65c8e2 - main
  40:     0x7f35fe2350b3 - __libc_start_main
  41:     0x5650da6570be - _start
  42:                0x0 - <unknown>
```

**Comment by ilyazzz** [comment]
Should be fixed. There was a bit of code leftover from debugging that crashes when overclocking is not enabled in the driver. Tell me if it works now.

**Comment by iRhonin** [comment]
> Should be fixed. There was a bit of code leftover from debugging that crashes when overclocking is not enabled in the driver. Tell me if it works now.

Yeap now working! Thanks man.
